Refactor, se agregar al controller métodos de para actualizar y  dar de baja una Organización.
alkemyTech/OT133-SERVER pull request #110
Opened 2022-02-19 12:51 UTC by maurodell

**Evidencia:**
![imagen](https://user-images.githubusercontent.com/68665811/154801515-8c14da23-6cd7-4632-ad80-27b5ed2a45d4.png)
![imagen](https://user-images.githubusercontent.com/68665811/154801526-8112a84a-2e30-4423-82f8-e9e91f7f9846.png)
![imagen](https://user-images.githubusercontent.com/68665811/154801546-5eddbc7d-a8ef-4d18-8294-5f8655f7528c.png)

2022-02-19 15:23 UTC, juanprodrigues commented on src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
> +	public void organizationCreateTest() throws IOException{
Falta test para probar excepciones. Por ejemplo nombre u otro atributo vacio...

2022-02-22 13:18 UTC, tomasanchez commented on src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
> +		assertTrue(ongList.size() == 1);
Para comparaciones es recomendable usar el 
`assertEquals`

2022-02-22 13:26 UTC, tomasanchez requested changes
Leer comentarios.
Ver pruebas de otros para tener mas idea con los tests.

2022-02-22 13:26 UTC, tomasanchez commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
>  package com.alkemy.ong.controller;
Entiendo que en las pruebas por ahi te encontraste con que faltaban metodos o habia que cambiar algo, 
pero el ticket solo pedia pruebas, **cambiar el controller esta fuera del scope**. 
Igual sin esto por ahi tus pruebas fallan.

Pero para tener en cuenta para el futuro. Cuando esto sucede, se "debe" (nosotros quedamos en esto) abrir un nuevo ticket en JIRA reportandolo como BUG y abrir un PR aparte

2022-02-22 13:26 UTC, tomasanchez commented on src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
>  package com.alkemy.ong.mapper;
Al igual que el controller - fuera del scope.
Leer comentario del controller.

2022-02-22 13:26 UTC, tomasanchez commented on src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
> +		assertNotNull(organizationController.create(ong));
Que significa `NotNull` ?
Que se esta probando ?
Que devuelva un ResponseEntity, que no salte ninguna excepcion que rompa el test.
En ninguno de tus casos probas que el resultado este bien, o que el codigo de operacion sea el esperado.

2022-02-22 13:47 UTC, maurodell commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
>  package com.alkemy.ong.controller;
ok

2022-02-22 13:47 UTC, closed without merging